# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_cleaning', models.CharField(max_length=155)),
                ('service_type', models.CharField(max_length=155)),
                ('extra_service', models.CharField(max_length=155)),
                ('square_feet', models.CharField(max_length=155)),
                ('check_if_carpet', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('apt_suite', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='FL', max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
    ]
