# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='SquareFeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_footage', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning', models.CharField(max_length=155)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestquotation',
            name='type_of_cleaning',
        ),
        migrations.AlterField(
            model_name='requestquotation',
            name='check_if_carpet',
            field=models.BooleanField(default=False, verbose_name='Check if you have carpet'),
        ),
        migrations.RemoveField(
            model_name='requestquotation',
            name='extra_service',
        ),
        migrations.RemoveField(
            model_name='requestquotation',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='requestquotation',
            name='square_feet',
        ),
        migrations.AddField(
            model_name='requestquotation',
            name='type_of_cleanings',
            field=models.ManyToManyField(related_name='type_of_cleaning', to='magicbroomsite.TypeOfCleaning'),
        ),
        migrations.AddField(
            model_name='requestquotation',
            name='extra_service',
            field=models.ManyToManyField(related_name='extra_service', to='magicbroomsite.ExtraService'),
        ),
        migrations.AddField(
            model_name='requestquotation',
            name='service_type',
            field=models.ManyToManyField(related_name='service_type', to='magicbroomsite.ServiceType'),
        ),
        migrations.AddField(
            model_name='requestquotation',
            name='square_feet',
            field=models.ManyToManyField(related_name='square_feet', to='magicbroomsite.SquareFeet'),
        ),
    ]
