# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0002_auto_20170903_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestQuotation',
            new_name='QuotationRequests',
        ),
    ]
