# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0003_auto_20170903_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeOfCleaning',
            new_name='HouseInformation',
        ),
        migrations.RenameField(
            model_name='houseinformation',
            old_name='cleaning',
            new_name='house',
        ),
        migrations.RemoveField(
            model_name='quotationrequests',
            name='type_of_cleanings',
        ),
        migrations.AddField(
            model_name='quotationrequests',
            name='home_info',
            field=models.ManyToManyField(related_name='home_info', to='magicbroomsite.HouseInformation'),
        ),
    ]
