# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0004_auto_20170905_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequests',
            name='booking_dates',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quotationrequests',
            name='rate_home',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='extra_service',
            field=models.ManyToManyField(blank='True', null='True', related_name='extra_service', to='magicbroomsite.ExtraService'),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
