# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0005_auto_20170905_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequests',
            name='booking_dates',
        ),
        migrations.AddField(
            model_name='quotationrequests',
            name='booking_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='quotationrequests',
            name='booking_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
