# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0006_auto_20170905_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='booking_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='extra_service',
            field=models.ManyToManyField(related_name='extra_service', to='magicbroomsite.ExtraService'),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
