# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0007_auto_20170905_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequests',
            name='booking_time',
        ),
    ]
