# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0008_remove_quotationrequests_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequests',
            name='extra_service',
        ),
        migrations.RemoveField(
            model_name='quotationrequests',
            name='service_type',
        ),
    ]
