# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0009_auto_20170905_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='home_info',
            field=models.ManyToManyField(related_name='home_infos', to='magicbroomsite.HouseInformation'),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='state',
            field=models.CharField(blank=True, default='FL', max_length=2, null=True),
        ),
    ]
