# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0014_auto_20170906_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='home_info_boost',
            field=models.CharField(choices=[('1 bed', '1 bed'), ('2 bed', '2 bed'), ('3 bed', '3 bed')], default='1 bed', max_length=155),
        ),
    ]
