# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:23
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0022_auto_20170908_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
