# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0023_auto_20170908_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
