# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0027_auto_20170908_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationrequests',
            name='service_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
