# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0028_quotationrequests_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='service_type',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
