# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0029_auto_20170909_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='service_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
