# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 13:14
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0030_auto_20170909_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='service_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onetime', 'One time'), ('Onceaweek', 'Once a week'), ('EveryTwoWeeks', 'Every Two Weeks'), ('EveryMonth', 'Every Month'), ('SpringDeepCleaning', 'Spring/Deep Cleaning'), ('Moveinout', 'Move-in/out')], max_length=71),
        ),
    ]
