# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0033_auto_20170911_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='referrer',
            field=models.CharField(default='Google', max_length=15),
        ),
    ]
