# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0037_auto_20170911_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='extra_service',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Clean Oven'), ('2', 'Clean Fridge'), ('3', 'Clean Interior Window'), ('4', 'Garage or Patio Sweep')], default=None, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='quotationrequests',
            name='referrer',
            field=models.CharField(choices=[('Google Search', 'Google Search'), ('Flyers', 'Flyers'), ('Newspaper Ad', 'Newspaper Ad'), ('Church Ad', 'Church Ad'), ('Other', 'Other')], max_length=15),
        ),
    ]
