# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0039_auto_20170911_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='referrer',
            field=models.CharField(choices=[('Google Search', 'Google Search'), ('Flyers', 'Flyers'), ('Newspaper Ad', 'Newspaper Ad'), ('Church Ad', 'Church Ad'), ('Other', 'Other')], max_length=15),
        ),
    ]
