# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0041_auto_20171128_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrequests',
            name='home_info',
        ),
    ]
