# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicbroomsite', '0042_remove_quotationrequests_home_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrequests',
            name='home_info_boost',
            field=models.CharField(default=None, max_length=155, verbose_name='Number of Bedrooms and Bathrooms'),
        ),
    ]
